"""Profile installation checks using isolated synthetic files, never a live host."""

from contextlib import redirect_stderr, redirect_stdout
import importlib.util
import io
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch


spec = importlib.util.spec_from_file_location(
    "install_hermes", Path(__file__).resolve().parents[1] / "scripts" / "install_hermes.py"
)
installer = importlib.util.module_from_spec(spec)
spec.loader.exec_module(installer)


class HermesInstallTests(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.area = Path(temp.name)
        self.root = self.area / "repo"
        self.home = self.area / "profile"
        resources = self.root / "components" / "hermes-orchestration"
        resources.mkdir(parents=True)
        for name, content in {
            "instructions.md": "# Shared behaviour\nVoice and prompts share one goal.\n",
            "capabilities.json": '{"capabilities": []}\n',
            "workflow-contracts.md": "# Workflow contracts\nCheck the actual tools.\n",
            "setup-contract.md": "# Deferred user setup\n",
            "settings.py": "# Installed settings helper\n",
        }.items():
            (resources / name).write_text(content, encoding="utf-8")
        self.skill = self.root / "skills" / "idea-to-content"
        (self.skill / "references").mkdir(parents=True)
        (self.skill / "SKILL.md").write_text("# Content creation\n", encoding="utf-8")
        (self.skill / "references" / "style.md").write_text("Keep it clear.\n", encoding="utf-8")

    def plan(self):
        return installer.build_plan(self.root, self.home)

    def apply(self):
        plan = self.plan()
        self.assertEqual([], plan["conflicts"])
        installer.apply_plan(plan)
        return plan

    def test_dry_run_does_not_create_profile(self):
        plan = self.plan()
        self.assertEqual([], plan["conflicts"])
        self.assertIn("SOUL.md", plan["changes"])
        self.assertFalse(self.home.exists())

    def test_apply_installs_complete_package_and_is_idempotent(self):
        self.apply()
        self.assertEqual("Keep it clear.\n", (self.home / "skills/idea-to-content/references/style.md").read_text())
        soul = (self.home / "SOUL.md").read_text()
        self.assertIn("You are Hermes", soul)
        self.assertIn((self.home / "hermes-agent-skills/capabilities.json").as_posix(), soul)
        self.assertEqual({}, self.plan()["changes"])

    def test_python_helper_installs_without_generated_bytecode(self):
        scripts = self.skill / "scripts"
        cache = scripts / "__pycache__"
        cache.mkdir(parents=True)
        (scripts / "helper.py").write_text("print('portable helper')\n")
        (cache / "helper.cpython-312.pyc").write_bytes(b"generated bytecode")
        (scripts / "legacy.pyc").write_bytes(b"old bytecode")
        self.apply()
        installed = self.home / "skills/idea-to-content/scripts"
        self.assertTrue((installed / "helper.py").is_file())
        self.assertFalse((installed / "__pycache__").exists())
        self.assertFalse((installed / "legacy.pyc").exists())

    def test_setup_resources_install_and_updates_preserve_user_settings(self):
        self.apply()
        resources = self.home / "hermes-agent-skills"
        self.assertTrue((resources / "setup-contract.md").exists())
        self.assertTrue((resources / "settings.py").exists())
        state = resources / "user-settings.json"
        state.write_text('{"revision":7,"daily_review":{"time":"07:30"}}')
        original = state.read_bytes()
        source = self.root / "components/hermes-orchestration/setup-contract.md"
        source.write_text(source.read_text() + "Updated guidance.\n")
        self.apply()
        self.assertEqual(state.read_bytes(), original)
        self.assertNotIn("hermes-agent-skills/user-settings.json", self.plan()["changes"])

    def test_existing_personality_and_configuration_are_preserved(self):
        self.home.mkdir()
        personality = b"\xef\xbb\xbf# Existing persona\r\nUse a quiet voice.\r\n"
        (self.home / "SOUL.md").write_bytes(personality)
        (self.home / "config.yaml").write_bytes(b"model: my-chosen-model\n")
        self.apply()
        self.assertTrue((self.home / "SOUL.md").read_bytes().startswith(personality))
        self.assertEqual(b"model: my-chosen-model\n", (self.home / "config.yaml").read_bytes())
        backups = list((self.home / "hermes-agent-skills/backups").glob("*/SOUL.md"))
        self.assertEqual([personality], [p.read_bytes() for p in backups])

    def test_unowned_different_skill_blocks_every_mutation(self):
        destination = self.home / "skills/idea-to-content/SKILL.md"
        destination.parent.mkdir(parents=True)
        destination.write_text("User skill", encoding="utf-8")
        plan = self.plan()
        self.assertTrue(plan["conflicts"])
        with self.assertRaises(installer.InstallError):
            installer.apply_plan(plan)
        self.assertEqual("User skill", destination.read_text())
        self.assertFalse((self.home / "SOUL.md").exists())

    def test_identical_unowned_content_is_adopted(self):
        destination = self.home / "skills/idea-to-content/SKILL.md"
        destination.parent.mkdir(parents=True)
        destination.write_bytes((self.skill / "SKILL.md").read_bytes())
        self.apply()
        state = json.loads((self.home / installer.STATE_PATH).read_text())
        self.assertIn("skills/idea-to-content/SKILL.md", state["files"])

    def test_source_upgrade_preserves_personal_edits_outside_block(self):
        self.apply()
        soul_path = self.home / "SOUL.md"
        original = soul_path.read_bytes()
        soul_path.write_bytes(b"A user's new preference.\n" + original + b"\nAnother preference.\n")
        policy = self.root / "components/hermes-orchestration/instructions.md"
        policy.write_text("# Updated behaviour\nUse current tools.\n", encoding="utf-8")
        self.apply()
        updated = soul_path.read_bytes()
        self.assertTrue(updated.startswith(b"A user's new preference.\n"))
        self.assertTrue(updated.endswith(b"\nAnother preference.\n"))
        self.assertIn(b"# Updated behaviour", updated)
        self.assertEqual({}, self.plan()["changes"])

    def test_owned_skill_edits_are_not_overwritten(self):
        self.apply()
        destination = self.home / "skills/idea-to-content/SKILL.md"
        destination.write_text("Local improvement", encoding="utf-8")
        self.assertIn("locally edited", " ".join(self.plan()["conflicts"]))
        self.assertEqual("Local improvement", destination.read_text())

    def test_managed_policy_edit_and_deletion_are_conflicts(self):
        self.apply()
        soul = self.home / "SOUL.md"
        original = soul.read_bytes()
        soul.write_bytes(original.replace(b"Voice and prompts", b"Local custom instructions"))
        self.assertIn("locally edited", " ".join(self.plan()["conflicts"]))
        soul.write_bytes(b"Only the user's personality remains.\n")
        self.assertIn("missing", " ".join(self.plan()["conflicts"]))

    def test_new_skill_is_discovered_without_changing_installer(self):
        self.apply()
        future = self.root / "skills" / "future-skill"
        future.mkdir()
        (future / "SKILL.md").write_text("# Future skill\n", encoding="utf-8")
        plan = self.apply()
        self.assertEqual(2, plan["skill_count"])
        self.assertTrue((self.home / "skills/future-skill/SKILL.md").exists())

    def test_removed_source_file_requires_explicit_migration(self):
        self.apply()
        (self.skill / "references/style.md").unlink()
        self.assertIn("explicit migration", " ".join(self.plan()["conflicts"]))
        self.assertTrue((self.home / "skills/idea-to-content/references/style.md").exists())

    def retired_fixture(self):
        package = self.root / "skills/research-brief"
        package.mkdir()
        source = package / "SKILL.md"
        source.write_text("Legacy research skill\n")
        self.apply()
        source.unlink()
        return self.home / "skills/research-brief/SKILL.md"

    def test_retired_owned_skill_is_backed_up_removed_and_idempotent(self):
        entry = self.retired_fixture()
        personal = entry.parent / "personal-notes.txt"
        personal.write_text("Keep my notes")
        plan = self.plan()
        self.assertEqual(plan["conflicts"], [])
        self.assertIsNone(plan["changes"]["skills/research-brief/SKILL.md"])
        self.assertTrue(entry.exists(), "preflight must remain read-only")
        backup = installer.apply_plan(plan)
        self.assertFalse(entry.exists())
        self.assertEqual((backup / "skills/research-brief/SKILL.md").read_text(), "Legacy research skill\n")
        self.assertEqual(personal.read_text(), "Keep my notes")
        self.assertNotIn("skills/research-brief/SKILL.md", json.loads((self.home / installer.STATE_PATH).read_text())["files"])
        self.assertEqual(self.plan()["changes"], {})

    def test_retired_locally_edited_skill_blocks_removal(self):
        entry = self.retired_fixture()
        entry.write_text("My edited research skill")
        plan = self.plan()
        self.assertIn("locally edited", " ".join(plan["conflicts"]))
        with self.assertRaises(installer.InstallError):
            installer.apply_plan(plan)
        self.assertEqual(entry.read_text(), "My edited research skill")

    def test_retired_unowned_skill_is_not_deleted(self):
        entry = self.home / "skills/research-brief/SKILL.md"
        entry.parent.mkdir(parents=True)
        entry.write_text("Independent user installation")
        plan = self.plan()
        self.assertIn("retired skill is unowned", " ".join(plan["conflicts"]))
        self.assertEqual(entry.read_text(), "Independent user installation")

    def test_retired_skill_edited_during_backup_is_preserved(self):
        entry = self.retired_fixture()
        plan = self.plan()
        old_state = (self.home / installer.STATE_PATH).read_bytes()
        original_write = installer.atomic_write
        def change_after_backup(path, content, **kwargs):
            original_write(path, content, **kwargs)
            if "backups" in path.parts and path.name == "SKILL.md":
                entry.write_text("Concurrent personal edit")
        with patch.object(installer, "atomic_write", side_effect=change_after_backup):
            with self.assertRaisesRegex(installer.InstallError, "Changed before removal"):
                installer.apply_plan(plan)
        self.assertEqual(entry.read_text(), "Concurrent personal edit")
        self.assertEqual((self.home / installer.STATE_PATH).read_bytes(), old_state)

    def test_preflight_race_is_detected_before_writing(self):
        self.apply()
        (self.skill / "SKILL.md").write_text("Version two", encoding="utf-8")
        plan = self.plan()
        destination = self.home / "skills/idea-to-content/references/style.md"
        destination.write_text("Concurrent edit", encoding="utf-8")
        with self.assertRaisesRegex(installer.InstallError, "Changed since preflight"):
            installer.apply_plan(plan)
        self.assertEqual("# Content creation\n", (self.home / "skills/idea-to-content/SKILL.md").read_text())
        self.assertFalse((self.home / installer.LOCK_PATH).exists())

    def test_personality_edit_during_backup_is_preserved(self):
        self.apply()
        policy = self.root / "components/hermes-orchestration/instructions.md"
        policy.write_text("# Updated behaviour\n", encoding="utf-8")
        plan = self.plan()
        soul = self.home / "SOUL.md"
        changed_personality = soul.read_bytes() + b"\nA concurrent user preference.\n"
        old_state = (self.home / installer.STATE_PATH).read_bytes()
        real_write = installer.atomic_write

        def edit_after_backup(path, content, **kwargs):
            real_write(path, content, **kwargs)
            if "backups" in path.parts and path.name == "SOUL.md":
                soul.write_bytes(changed_personality)

        with patch.object(installer, "atomic_write", side_effect=edit_after_backup):
            with self.assertRaisesRegex(installer.InstallError, "Changed before replacement"):
                installer.apply_plan(plan)
        self.assertEqual(changed_personality, soul.read_bytes())
        self.assertEqual(old_state, (self.home / installer.STATE_PATH).read_bytes())
        self.assertFalse((self.home / installer.LOCK_PATH).exists())

    def test_final_check_refuses_ownership_commit_after_concurrent_edit(self):
        self.apply()
        (self.skill / "SKILL.md").write_text("Version two", encoding="utf-8")
        plan = self.plan()
        destination = self.home / "skills/idea-to-content/SKILL.md"
        unchanged_reference = self.home / "skills/idea-to-content/references/style.md"
        old_state = (self.home / installer.STATE_PATH).read_bytes()
        real_write = installer.atomic_write

        def edit_after_replacement(path, content, **kwargs):
            real_write(path, content, **kwargs)
            if path == destination:
                unchanged_reference.write_text("Concurrent style improvement", encoding="utf-8")

        with patch.object(installer, "atomic_write", side_effect=edit_after_replacement):
            with self.assertRaisesRegex(installer.InstallError, "Changed before state commit"):
                installer.apply_plan(plan)
        self.assertEqual("Concurrent style improvement", unchanged_reference.read_text())
        self.assertEqual(old_state, (self.home / installer.STATE_PATH).read_bytes())
        self.assertFalse((self.home / installer.LOCK_PATH).exists())

    def test_concurrent_installer_lock_blocks_then_releases(self):
        plan = self.plan()
        lock = self.home / installer.LOCK_PATH
        with installer.installation_lock(self.home):
            with self.assertRaisesRegex(installer.InstallError, "Installer lock exists"):
                installer.apply_plan(plan)
            self.assertTrue(lock.is_file())
            self.assertFalse((self.home / "SOUL.md").exists())
        self.assertFalse(lock.exists())
        installer.apply_plan(plan)
        self.assertFalse(lock.exists())
        self.assertEqual({}, self.plan()["changes"])

    def test_stale_lock_is_preserved_with_recovery_instruction(self):
        plan = self.plan()
        lock = self.home / installer.LOCK_PATH
        lock.parent.mkdir(parents=True)
        lock.write_bytes(b"Previous interrupted run")
        with self.assertRaisesRegex(installer.InstallError, "remove only this stale lock"):
            installer.apply_plan(plan)
        self.assertEqual(b"Previous interrupted run", lock.read_bytes())
        self.assertFalse((self.home / "SOUL.md").exists())

    def test_overlap_and_traversal_are_rejected(self):
        with self.assertRaisesRegex(installer.InstallError, "overlap"):
            installer.build_plan(self.root, self.root / "skills" / "profile")
        with self.assertRaisesRegex(installer.InstallError, "overlap"):
            installer.build_plan(self.root, self.root / "components")
        with self.assertRaisesRegex(installer.InstallError, "overlap"):
            installer.build_plan(self.root, self.area)
        for relative in ("../outside", "/absolute", "C:/absolute", "skills\\..\\outside"):
            with self.assertRaises(installer.InstallError):
                installer.target_path(self.home, relative)

    def test_ignored_staging_outside_source_trees_is_permitted(self):
        staging = self.root / "test-results" / "staged-profile"
        plan = installer.build_plan(self.root, staging)
        self.assertEqual([], plan["conflicts"])
        installer.apply_plan(plan)
        self.assertTrue((staging / "SOUL.md").is_file())

    def test_linked_destination_is_rejected(self):
        self.home.mkdir()
        outside = self.area / "outside"
        outside.mkdir()
        try:
            (self.home / "skills").symlink_to(outside, target_is_directory=True)
        except OSError:
            self.skipTest("Creating symlinks is not permitted on this host")
        with self.assertRaisesRegex(installer.InstallError, "Linked paths"):
            self.plan()
        self.assertEqual([], list(outside.iterdir()))

    def test_corrupt_state_and_block_markers_are_rejected(self):
        self.home.mkdir()
        (self.home / "SOUL.md").write_bytes(installer.START + b"broken")
        with self.assertRaisesRegex(installer.InstallError, "markers"):
            self.plan()
        (self.home / "SOUL.md").unlink()
        state = self.home / installer.STATE_PATH
        state.parent.mkdir()
        state.write_text('{"schema_version": 9}', encoding="utf-8")
        with self.assertRaisesRegex(installer.InstallError, "Unsupported installation state"):
            self.plan()

    def test_cli_check_detects_missing_install_without_writing(self):
        with patch.object(installer, "ROOT", self.root), redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            self.assertEqual(1, installer.main(["--hermes-home", str(self.home), "--check"]))
            self.assertFalse(self.home.exists())
            self.assertEqual(0, installer.main(["--hermes-home", str(self.home), "--apply"]))
            self.assertEqual(0, installer.main(["--hermes-home", str(self.home), "--check"]))


if __name__ == "__main__":
    unittest.main()
